### ISSUE TITLE
How to convert .vcg file to .rviz

### ISSUE THREAD

**Issue by The-gimmickk** [ethz-asl/ethzasl_icp_mapping#50]
How can I convert .vcg files to .rviz files as these files are not being launched, Please suggest something!

**Comment by pomerlef** [comment]
Right, that seems outdated since a while (2013).

I suggest you to start from scratch with an empty rviz. Click on the add button (lower-left corner), select the tab By topic, then bring the pointcloud2 topics you wish to see.

If you're not sure in general how to use rviz, you can check this user guide: http://wiki.ros.org/rviz/UserGuide

**Comment by The-gimmickk** [comment]
Sorry, but this
